version: "3.9"

services:
  rebeldes-api:
    container_name: rebels-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - docker-postgres

  docker-postgres:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres